"""set UC titleXuser_id

Revision ID: 75f92867bdff
Revises: ccde5054e82c
Create Date: 2024-08-20 06:05:27.240632

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75f92867bdff"
down_revision: Union[str, None] = "ccde5054e82c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("todos_title_key", "todos", type_="unique")
    op.create_unique_constraint("user_title_uc", "todos", ["user_id", "title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_title_uc", "todos", type_="unique")
    op.create_unique_constraint("todos_title_key", "todos", ["title"])
    # ### end Alembic commands ###
