"""Add users table

Revision ID: ccde5054e82c
Revises: 213f51651498
Create Date: 2024-08-05 07:57:53.582894

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ccde5054e82c"
down_revision: Union[str, None] = "213f51651498"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("salt", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )

    # todosテーブルのレコードを空にする。
    op.execute("DELETE FROM todos")

    op.add_column("todos", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_todos_user_id", "todos", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_todos_user_id", "todos", type_="foreignkey")
    op.drop_column("todos", "user_id")
    op.drop_table("users")
    # ### end Alembic commands ###
