services:
  db:
    image: postgres:15
    container_name: postgres
    volumes:
      - ./db/pg_init:/docker-entrypoint-initdb.d
      - ./db/pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:  
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_db
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  app:
    build: 
      context: .  # ビルド時のローカルのコンテキスト
      dockerfile: ./app/Dockerfile.dev
    volumes:
      - ./app:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:  
      - ./app/.env