services:
  db:
    image: postgres:15
    container_name: postgres
    volumes:
      - ./init_db.d:/docker-entrypoint-initdb.d
      - ./docker/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:  
      - .env

  app:
    build: 
      context: .  # ビルド時のローカルのコンテキスト
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:  
      - .env