name: ci

# このワークフローがいつ実行されるかを定義
on:
  push:
    branches: main

jobs:
  # コードのフォーマット
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install black
        run: |
          pip install black

      - name: Format code
        run: |
          cd app
          black .

  # PEP8のチェック
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install flake8
        run: |
          pip install flake8

      - name: Lint code
        run: |
          cd app
          flake8

  # テストジョブ
  test:
    runs-on: ubuntu-latest
    needs: [fmt, lint]  # fmtとlintジョブの後に実行
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run tests
        env:
          SECRET_KEY: test
          SQLALCHEMY_DATABASE_URL: sqlite://
        run: pytest
